# Generated by Django 6.0 on 2026-03-07 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familya')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='couriers/avatars/', verbose_name='Avatar rasm')),
                ('car_number', models.CharField(max_length=20, unique=True, verbose_name='Mashina raqami')),
                ('car_name', models.CharField(max_length=100, verbose_name='Mashina nomi')),
                ('car_capacity', models.DecimalField(decimal_places=2, help_text='Mashina necha kub metr yuk tashiydi (masalan: 10.00)', max_digits=10, verbose_name="Mashina sig'imi (kub metr)")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqt')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='courier_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Kurer',
                'verbose_name_plural': 'Kurerlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
