# Generated by Django 6.0 on 2026-02-17 00:00

from django.db import migrations, models


def populate_total_stock_in(apps, schema_editor):
    Product = apps.get_model("catalog", "Product")
    for product in Product.objects.all().only("id", "stock", "total_stock_in"):
        if product.total_stock_in == 0 and product.stock:
            Product.objects.filter(pk=product.pk).update(total_stock_in=product.stock)


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cost_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="total_stock_in",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="total_stock_out",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunPython(populate_total_stock_in, migrations.RunPython.noop),
    ]
