# Generated by Django 6.0 on 2026-03-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_finance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Mahsulotning hajmi kub metrda', max_digits=10, verbose_name='Hajm (kub metr)'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Mahsulotning og'irligi kilogrammda", max_digits=10, verbose_name="Og'irlik (kg)"),
        ),
    ]
